name: 'Chromatic'
on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
          # the following 2 lines are the key
          always-auth: true
          scope: '@chargepoint'

      - name: Setup project level .npmrc
        run: |
          echo "Writing out project level .npmrc file..."
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > .npmrc

      - name: Install package dependencies
        run: |
          echo "Installing yarn package dependencies..."
          yarn

      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: 259ccb94cb08
